# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pchQc245wN0qHtqcX1lKStU54_izqPsO
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# --- Title ---
st.title("FEMA Disaster Relief Dashboard")

# --- Load FEMA dataset ---
# Option 1: Read from same repo as app
df = pd.read_csv("fema_sample.csv") # NO CONTENT!

# Option 2: Or use a raw GitHub link
#df = pd.read_csv("https://raw.githubusercontent.com/grosskm2-crypto/FEMA-Dashboard-INFO450/main/fema_sample.csv")

# --- Data Preview ---
st.subheader("Data Preview")
st.write(df.head())

# --- Histogram of Repair Amount ---
st.subheader("Histogram of Repair Amount")
fig_hist = px.histogram(
    df,
    x="repairAmount",
    nbins=30,
    title="Distribution of Repair Amounts"
)
st.plotly_chart(fig_hist)

# --- Boxplot of Repair Amount by TSA Eligibility ---
st.subheader("Boxplot: Repair Amount by TSA Eligibility")
fig_box = px.box(
    df,
    x="tsaEligible",
    y="repairAmount",
    title="Repair Amount by TSA Eligibility",
    labels={
        "tsaEligible": "TSA Eligible (1 = Yes, 0 = No)",
        "repairAmount": "Repair Amount"
    }
)
st.plotly_chart(fig_box)